### ISSUE TITLE
Good to see Angular Version

### ISSUE THREAD

**Issue by deepak458** [csotomon/angularAdminLTE#5]
So when we get basic version of this project, i'm exited for this project.

**Comment by csotomon** [comment]
Hi, i hope that the next week the stater module will be at 100% and the dashboard 1 module at 70%, please check de develop branch.

**Comment by deepak458** [comment]
@csotomon sure, I'm waiting for it

**Comment by deepak458** [comment]
@csotomon so when we expect release date ?

**Comment by csotomon** [comment]
@deepak458 , now in the dev branch you can see the starter (/starter) and the dashboard v1 ( /dashboard/v1 ), dashboard v2 ( /dashboard/v2 ), dashboard v3 ( /dashboard/v3 ) pages
